# Generated by Django 4.0 on 2021-12-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=None),
        ),
    ]
