# Generated by Django 4.0 on 2021-12-30 18:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertiser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('title', models.CharField(max_length=500)),
                ('advetiser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='advertiser.advertiser')),
            ],
        ),
    ]
